/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Nastavnik;
import domain.OblikNastave;
import domain.Predmet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import logic.Controller;

/**
 *
 * @author Ognjen
 */
public class FrmDodajAngazovanje extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDodajAngazovanje.class.getName());
    private Nastavnik ulogovaniNastavnik;
   // private FrmGlavna glavnaForma;
    private FrmTabelaPredmeta formaZaOsvezavanje;
    
    
    /**
     * Creates new form FrmDodajAngazovanje
     */
    public FrmDodajAngazovanje() {
        
    }
    public FrmDodajAngazovanje(Nastavnik ulogovaniNastavnik, FrmTabelaPredmeta formaZaOsvezavanje){
        initComponents();
        this.ulogovaniNastavnik = ulogovaniNastavnik;
        this.formaZaOsvezavanje = formaZaOsvezavanje;
        setTitle("Dodavanje novog angazovanja za: " + ulogovaniNastavnik.getIme());
        
        try {
            popuniKomboPolja();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri inicijalizaciji: " + e.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }
    
    private void popuniKomboPolja() throws Exception{
        // 1. popunjavanje predmeta
        List<Predmet> predmeti = Controller.getInstance().ucitajSvePredmete();
        cmbPredmet.setModel(new DefaultComboBoxModel(predmeti.toArray()));
        
        List<OblikNastave> oblici = Controller.getInstance().ucitajSveObliciNastave();
        cmbOblikNastave.setModel(new DefaultComboBoxModel(oblici.toArray()));
        
        cmbPredmet.setSelectedIndex(-1);
        cmbOblikNastave.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPredmet = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbOblikNastave = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 25));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Predmet");
        getContentPane().add(jLabel1, new java.awt.GridBagConstraints());

        cmbPredmet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbPredmet, new java.awt.GridBagConstraints());

        jLabel2.setText("Oblik nastave:");
        getContentPane().add(jLabel2, new java.awt.GridBagConstraints());

        cmbOblikNastave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbOblikNastave, new java.awt.GridBagConstraints());

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacuvaj, new java.awt.GridBagConstraints());

        btnPonisti.setText("Ponisti");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPonisti, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Predmet izabraniPredmet = (Predmet) cmbPredmet.getSelectedItem();
        OblikNastave izabraniOblik = (OblikNastave) cmbOblikNastave.getSelectedItem();
        
        if(izabraniPredmet == null || izabraniOblik == null){
            JOptionPane.showMessageDialog(this, "Morate izabrati i predmet i oblik nastave", "Upozerenja", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            Controller.getInstance().sacuvajAngazovanje(ulogovaniNastavnik, izabraniPredmet, izabraniOblik);
            JOptionPane.showMessageDialog(this, "Angazovanje je uspesno sacuvano","Uspeh", JOptionPane.INFORMATION_MESSAGE);
            
            if(formaZaOsvezavanje != null){
                formaZaOsvezavanje.osveziTabelu();
            }
            
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri snimanju angazovanje: " + e.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);            
        }
        
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnPonistiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cmbOblikNastave;
    private javax.swing.JComboBox<String> cmbPredmet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
