/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Nastavnik;
import domain.Predmet;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logic.Controller;

/**
 *
 * @author Ognjen
 */
public class FrmGlavna extends javax.swing.JFrame {
    
  
    
    private Nastavnik ulogovaniNastavnik;
    Controller controller = new Controller();
    private JComboBox<Predmet> jcbPredmeti;
    private JButton jbtnOtvoriOblike;

    /**
     * Creates new form FrmGlavna
     */
    
    /*
    public FrmGlavna() {
        initComponents();
    }
    */
    public FrmGlavna(Nastavnik ulogovaniNastavnik) {
        this.ulogovaniNastavnik = ulogovaniNastavnik;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glavna forma - " + ulogovaniNastavnik.getIme());
        popuniPredmete();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuNastavnik = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuNastavnik.setText("Nastavnik");

        jMenuItem1.setText("new Nastavnik");
        menuNastavnik.add(jMenuItem1);

        jMenuItem2.setText("show Nastavnik");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuNastavnik.add(jMenuItem2);

        jMenuBar1.add(menuNastavnik);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popuniPredmete(){
        try {
            List<Predmet> predmeti = controller.ucitajAngazovanePredmete(ulogovaniNastavnik);
            jcbPredmeti.setModel(new DefaultComboBoxModel(predmeti.toArray()));
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Greška pri učitavanju predmeta.", "Greška", JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void jbtnOtvoriOblikeActionPerformed(java.awt.event.ActionEvent evt){
        Predmet selektovaniPredmet = (Predmet) jcbPredmeti.getSelectedItem();
        if(selektovaniPredmet != null){
            FrmOblikNastave forma = new FrmOblikNastave(this,true, ulogovaniNastavnik, selektovaniPredmet);
            forma.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Izaberite predmet.", "Upozorenje", JOptionPane.WARNING_MESSAGE);
        }
        
    }
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuNastavnik;
    // End of variables declaration//GEN-END:variables
}
