/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.form;

import domain.Nastavnik;
import domain.OblikNastave;
import domain.Predmet;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import logic.Controller;

/**
 *
 * @author Ognjen
 */
public class FrmOblikNastave extends javax.swing.JDialog {
    
    Controller controller = new Controller();
    private Nastavnik nastavnik;
    private Predmet predmet;
    
    private JLabel lblPredmetNaziv;
    private JTable jtblOblici;
    
    

    /**
     * Creates new form FrmOblikNastave
     */
    public FrmOblikNastave(java.awt.Frame parent, boolean modal, Nastavnik n, Predmet p) {
        super(parent, modal);
        this.nastavnik = n;
        this.predmet = p;
        
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Oblici nastave");
    }

    
    
    private void popuniTabelu(){
        try {
            List<OblikNastave> oblici = controller.ucitajObliciNastave(nastavnik, predmet);
            //ModelTabeleOblici model = new ModelTabeleOblici(oblici);
            //jtblOblici.setModel(model);
            
            lblPredmetNaziv.setText(predmet.getNaziv());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Greška pri učitavanju oblika nastave.",
                "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
