/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Nastavnik;
import javax.swing.JOptionPane;
import ui.component.table.TabelaPredmetaModel;

/**
 *
 * @author Ognjen
 */
public class FrmTabelaPredmeta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmTabelaPredmeta.class.getName());

    private Nastavnik ulogovaniNastavnik;
    
    /**
     * Creates new form FrmTabelaPredmeta
     */
    
    
    public FrmTabelaPredmeta() {
    }

    public FrmTabelaPredmeta(Nastavnik ulogovaniNastavnik) {
        initComponents();
        this.ulogovaniNastavnik = ulogovaniNastavnik;
        setTitle("Predmeti angažovanja za: " + ulogovaniNastavnik.getIme() + " " + ulogovaniNastavnik.getPrezime());
        try {
            pripremiTabelu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja predmeta: " + ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPredmeti = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Predmeti ");

        tblPredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPredmeti);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmTabelaPredmeta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPredmeti;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() throws Exception {
        TabelaPredmetaModel model = new TabelaPredmetaModel(ulogovaniNastavnik);
        tblPredmeti.setModel(model);
        model.ucitajPredmete();
    }
}
